// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '           'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BA2kxqa0PmsYoeFWRbh7D-SFc_KFZrs',
    appId: '1:591676704670:web:7f52c8150d436c6a3e388f',
    messagingSenderId: '591676704670',
    projectId: 'testhub2-project',
    authDomain: 'testhub2-project.firebaseapp.com',
    storageBucket: 'testhub2-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGfVD_O5JyJINB1vNn2-eAT9ik4NRbxA',
    appId: '1:591676704670:android:8de0b46b77c7d02c3e388f',
    messagingSenderId: '591676704670',
    projectId: 'testhub2-project',
    storageBucket: 'testhub2-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrnc8r0yUpavREEjfecr9AzXlIIUq0Qpw',
    appId: '1:591676704670:ios:e39ec8803a9a72213e388f',
    messagingSenderId: '591676704670',
    projectId: 'testhub2-project',
    storageBucket: 'testhub2-project.firebasestorage.app',
    iosBundleId: 'com.testhub2.testhub2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrnc8r0yUpavREEjfecr9AzXlIIUq0Qpw',
    appId: '1:591676704670:ios:e39ec8803a9a72213e388f',
    messagingSenderId: '591676704670',
    projectId: 'testhub2-project',
    storageBucket: 'testhub2-project.firebasestorage.app',
    iosBundleId: 'com.testhub2.testhub2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BA2kxqa0PmsYoeFWRbh7D-SFc_KFZrs',
    appId: '1:591676704670:web:bd53bed46bdb3f133e388f',
    messagingSenderId: '591676704670',
    projectId: 'testhub2-project',
    authDomain: 'testhub2-project.firebaseapp.com',
    storageBucket: 'testhub2-project.firebasestorage.app',
  );

}
